apiVersion: v1
kind: Service
metadata:
  name: dev-env
  labels:
    app: dev-env
spec:
  selector:
    app: dev-env
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
